name: bob.paper.icb2019.gradgpad
channels:
  - https://www.idiap.ch/software/bob/conda
  - defaults
  - conda-forge
dependencies:
  - phantomjs=2.1.1=1
  - backports=1.0=py36_1
  - blas=1.0=mkl
  - bleach=1.5.0=py36_0
  - bokeh=1.0.4=py36_0
  - boost=1.65.1=py36_4
  - bzip2=1.0.6=h1de35cc_5
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2018.11.29=py36_0
  - click=7.0=py36_0
  - click-plugins=1.0.4=py36_0
  - configobj=5.0.6=py36_1
  - cycler=0.10.0=py36hfc81398_0
  - docopt=0.6.2=py36_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - gitdb2=2.0.5=py36_0
  - gitpython=2.1.11=py36_0
  - glib=2.56.2=hd9629dc_0
  - graphite2=1.3.13=h2098e52_0
  - h5py=2.7.1=py36h39cdac5_0
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.1=ha036c08_1
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.1=144
  - jasper=1.900.1=h1f36771_4
  - jinja2=2.10=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.0.1=py36h0a44026_0
  - libboost=1.65.1=hcc95346_4
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.36=ha441bb4_0
  - libprotobuf=3.4.1=h326466f_0
  - libtiff=4.0.10=hcb84e12_2
  - libvpx=1.6.1=h057a404_0
  - libxml2=2.9.9=hab757c2_0
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.0=py36h1de35cc_0
  - matplotlib=3.0.2=py36h54f8f79_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - mock=2.0.0=py36hd48142b_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.15.4=py36hacdab7b_0
  - numpy-base=1.15.4=py36h6575580_0
  - olefile=0.46=py36_0
  - opencv=3.3.1=py36h60a5f38_1
  - openssl=1.1.1a=h1de35cc_0
  - packaging=19.0=py36_0
  - pandas=0.24.1=py36h0a44026_0
  - pbr=5.1.1=py36_0
  - pcre=8.42=h378b8a2_0
  - pillow=5.4.1=py36hb68e598_0
  - pip=19.0.1=py36_0
  - pixman=0.36.0=h1de35cc_0
  - py-boost=1.65.1=py36h1439ea1_4
  - py-cpuinfo=4.0.0=py36_0
  - pyparsing=2.3.1=py36_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.9=py36_0
  - pyyaml=3.13=py36h1de35cc_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.20.2=py36h27c97d8_0
  - scipy=1.2.1=py36h1410ff5_0
  - setuptools=40.8.0=py36_0
  - six=1.12.0=py36_0
  - smmap2=2.0.5=py36_0
  - sphinx_rtd_theme=0.4.2=py36_0
  - sqlalchemy=1.2.18=py36h1de35cc_0
  - sqlite=3.26.0=ha441bb4_0
  - tabulate=0.8.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py36h1de35cc_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - backports.weakref=1.0rc1=py36_0
  - bob.bio.base=4.0.0=py36h9e540f5_0
  - bob.bio.face=4.0.0=py36h605e89b_0
  - bob.bio.video=3.4.2=py36hf2dec60_0
  - bob.blitz=2.0.16=py36hb255e9f_0
  - bob.core=2.2.1=py36hb255e9f_0
  - bob.db.atnt=2.0.12=py36hf2dec60_0
  - bob.db.base=3.0.1=py36h28a5d26_0
  - bob.db.maskattack=0.0.1=py36h9e5790e_0
  - bob.db.msu_mfsd_mod=2.2.3=py_0
  - bob.db.replay=3.0.2=py_0
  - bob.db.replaymobile=1.1.5=py36hcc0c415_0
  - bob.extension=3.1.0=py36h53aaba6_0
  - bob.io.base=3.0.4=py36h67a578e_0
  - bob.io.image=2.4.2=py36h5820f71_0
  - bob.io.matlab=2.0.12=py36h3c378cb_0
  - bob.io.video=2.1.1=py36h72fd480_1
  - bob.ip.base=2.2.2=py36h346b26f_0
  - bob.ip.color=2.0.12=py36hb255e9f_0
  - bob.ip.dlib=1.0.5=py36hb8ffe50_0
  - bob.ip.draw=2.0.11=py36hfc35235_0
  - bob.ip.facedetect=2.1.6=py36h20e3e68_0
  - bob.ip.facelandmarks=1.0.6=py36h8e9bb8c_0
  - bob.ip.flandmark=2.1.8=py36h20e3e68_0
  - bob.ip.gabor=2.0.13=py36h3065f49_0
  - bob.ip.qualitymeasure=1.1.1=py36h76d48dc_0
  - bob.ip.skincolorfilter=0.0.5=py36hfa564a4_0
  - bob.learn.activation=2.0.12=py36hb255e9f_0
  - bob.learn.boosting=2.0.15=py36h1d464f9_0
  - bob.learn.em=2.1.2=py36h3065f49_0
  - bob.learn.libsvm=2.1.1=py36heeed554_0
  - bob.learn.linear=2.1.4=py36h1d464f9_0
  - bob.learn.mlp=2.1.8=py36hb255e9f_0
  - bob.math=3.1.2=py36he190528_0
  - bob.measure=4.0.0=py36h30cf29c_0
  - bob.pad.base=2.1.0=py36hf2dec60_0
  - bob.pad.face=2.1.0=py36h7f092e8_0
  - bob.rppg.base=2.0.2=py36hf2dec60_0
  - bob.sp=2.0.12=py36hd9e1d88_0
  - cyvlfeat=0.4.6=py36hbf625f4_4
  - dlib=19.7=py36h080864a_1
  - ffmpeg=3.4=h3b64a03_1
  - giflib=5.1.4=h9a61bd3_4
  - gridtk=1.6.2=py36h155302e_0
  - html5lib=0.9999999=py36_0
  - libblitz=1.0.1=hd7a9176_0
  - libmatio=1.5.11=h170b5ee_0
  - libsvm=3.22=h095a671_0
  - menpo=0.8.1=py36h380936f_6
  - menpofit=0.5.0=py36_0
  - openh264=1.7.0=h89e8454_1
  - protobuf=3.3.0=py36_0
  - tensorflow=1.2.1=py36_0
  - vlfeat=0.9.21=h2d5a098_0
  - bob.db.msu_mfsd_mod=2.2.3
  - bob.db.replay=3.0.2
  - bob.db.replaymobile
  - bob.db.maskattack
  - pip:
    - absl-py==0.7.0
    - astor==0.7.1
    - cloudpickle==0.8.0
    - coloredlogs==10.0
    - dask==1.1.1
    - decorator==4.3.2
    - dominate==2.3.5
    - gast==0.2.2
    - grpcio==1.18.0
    - humanfriendly==4.18
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - networkx==2.2
    - nose==1.3.7
    - progress==1.4
    - pywavelets==1.0.1
    - scikit-image==0.14.2
    - selenium==3.141.0
    - tensorboard==1.12.2
    - termcolor==1.1.0
    - toolz==0.9.0
    - urllib3==1.24.1
    - xgboost==0.81

