name: bob.paper.icb2019.gradgpad
channels:
  - https://www.idiap.ch/software/bob/conda
  - defaults
  - conda-forge
dependencies:
  - libffi=3.2.1=hf484d3e_1005
  - libgcc-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=7.3.0=hdf63c60_0
  - libxgboost=0.81=hf484d3e_1000
  - ncurses=6.1=hf484d3e_1002
  - pip=19.0.3=py36_0
  - py-xgboost=0.81=py36hf484d3e_1000
  - python=3.6.7=h381d211_1004
  - readline=7.0=hf8c457e_1001
  - setuptools=40.8.0=py36_0
  - sqlite=3.26.0=h67949de_1000
  - tk=8.6.9=h84994c4_1000
  - wheel=0.33.1=py36_0
  - xgboost=0.81=py36hf484d3e_1000
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - _py-xgboost-mutex=2.0=cpu_0
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.0=py36_0
  - astor=0.7.1=py36_0
  - blas=1.0=mkl
  - bokeh=1.0.4=py36_0
  - boost=1.65.1=py36_4
  - bzip2=1.0.6=h14c3975_5
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.11.29=py36_0
  - click=7.0=py36_0
  - click-plugins=1.0.4=py36_0
  - coloredlogs=10.0=py36_0
  - configobj=5.0.6=py36_1
  - cycler=0.10.0=py36_0
  - dbus=1.13.6=h746ee38_0
  - docopt=0.6.2=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - gitdb2=2.0.5=py36_0
  - gitpython=2.1.11=py36_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.7.1=py36h3585f63_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.1=h9caa474_1
  - humanfriendly=4.17=py36_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - jasper=1.900.1=hd497a04_4
  - jinja2=2.10=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.6=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libboost=1.65.1=habcd387_4
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.6.1=h888fd40_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.0.2=py36h5429711_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - mock=2.0.0=py36_0
  - numpy=1.16.2=py36h7e9f1db_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - opencv=3.3.1=py36h0a11808_0
  - openssl=1.1.1b=h7b6447c_1
  - packaging=19.0=py36_0
  - pandas=0.24.1=py36he6710b0_0
  - pbr=5.1.1=py36_0
  - pcre=8.42=h439df22_0
  - pillow=5.4.1=py36h34e0f95_0
  - pixman=0.36.0=h7b6447c_0
  - protobuf=3.6.1=py36he6710b0_0
  - py-boost=1.65.1=py36hf484d3e_4
  - py-cpuinfo=4.0.0=py36_0
  - pyparsing=2.3.1=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - python-dateutil=2.8.0=py36_0
  - pytz=2018.9=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - scikit-learn=0.20.2=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - smmap2=2.0.5=py36_0
  - sphinx_rtd_theme=0.4.2=py36_0
  - sqlalchemy=1.2.18=py36h7b6447c_0
  - tabulate=0.8.2=py36_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=mkl_py36h69b6ba0_0
  - tensorflow-base=1.12.0=mkl_py36h3c3e929_0
  - termcolor=1.1.0=py36_1
  - tornado=5.1.1=py36h7b6447c_0
  - werkzeug=0.14.1=py36_0
  - yaml=0.1.7=had09818_2
  - zstd=1.3.7=h0b5b093_0
  - bob.bio.base=4.0.0=py36h9e540f5_0
  - bob.bio.face=4.0.0=py36h605e89b_0
  - bob.bio.video=3.4.2=py36hf2dec60_0
  - bob.blitz=2.0.16=py36hac2ea6f_0
  - bob.core=2.2.1=py36hac2ea6f_0
  - bob.db.atnt=2.0.12=py36hf2dec60_0
  - bob.db.base=3.0.1=py36h28a5d26_0
  - bob.extension=3.1.0=py36h6c8ecfd_0
  - bob.io.base=3.0.4=py36h12a88d4_0
  - bob.io.image=2.4.2=py36hd33571a_0
  - bob.io.matlab=2.0.12=py36h5bf78fe_0
  - bob.io.video=2.1.1=py36hd1ff1a4_1
  - bob.ip.base=2.2.2=py36h2b31b38_0
  - bob.ip.color=2.0.12=py36hac2ea6f_0
  - bob.ip.dlib=1.0.5=py36hb8ffe50_0
  - bob.ip.draw=2.0.11=py36hbc316f1_0
  - bob.ip.facedetect=2.1.6=py36hbf20c1f_0
  - bob.ip.facelandmarks=1.0.6=py36h8e9bb8c_0
  - bob.ip.flandmark=2.1.8=py36hbf20c1f_0
  - bob.ip.gabor=2.0.13=py36h5d07071_0
  - bob.ip.qualitymeasure=1.1.1=py36hcd7cccb_0
  - bob.ip.skincolorfilter=0.0.5=py36hfa564a4_0
  - bob.learn.activation=2.0.12=py36hac2ea6f_0
  - bob.learn.boosting=2.0.15=py36hf9a62a4_0
  - bob.learn.em=2.1.2=py36h5d07071_0
  - bob.learn.libsvm=2.1.1=py36h7de4692_0
  - bob.learn.linear=2.1.4=py36hf9a62a4_0
  - bob.learn.mlp=2.1.8=py36hac2ea6f_0
  - bob.math=3.1.2=py36he85555e_0
  - bob.measure=4.0.0=py36h74400ff_0
  - bob.pad.base=2.1.0=py36hf2dec60_0
  - bob.pad.face=2.1.0=py36h7f092e8_0
  - bob.rppg.base=2.0.2=py36hf2dec60_0
  - bob.sp=2.0.12=py36h3b40046_0
  - cyvlfeat=0.4.6=py36hd9be493_4
  - dlib=19.7=py36hdafcfc0_1
  - ffmpeg=3.4=hdec9c9a_1
  - giflib=5.1.4=h63890e4_4
  - gridtk=1.6.2=py36h155302e_0
  - libblitz=1.0.1=h5c30f38_0
  - libmatio=1.5.11=ha500df2_0
  - libsvm=3.22=h4f306d9_0
  - menpo=0.8.1=py36hfd4ac0d_6
  - menpofit=0.5.0=py36_0
  - openh264=1.7.0=hc521636_1
  - vlfeat=0.9.21=h18fa195_0
  - bob.db.msu_mfsd_mod=2.2.3
  - bob.db.replay=3.0.2
  - bob.db.replaymobile
  - bob.db.maskattack
  - pip:
    - enum-compat==0.0.2
    - progress==1.4


